[package]
name = "anonnet-common"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
hex = "0.4"

[dev-dependencies]
bincode = "1.3"
